export default {
    products: [
        {
            _id: '1',
            name: 'Soho wool tuxedo',
            category: 'Tuxedo',
            image: '/images/d1.jpg',
            description: 'Tuxedo from the Soho line with a young, sophisticated design that combines the details of traditional tailoring with the modern charisma reflected in its name. Made from solid wool twill with grosgrain details, this single-breasted jacket features two-button fastening, notched lapels, welt pockets including a breast pocket, and rear side vents. Length 73.5 cm / 29 in. The classic trousers have French pockets to the front and rear buttoned welt pockets. Covered zip and button fastening. Leg cuff width 19 cm / 7.5 in. Lined. Made in Italy.',
            price: 8995,
            brand: 'Armani',
            rating: 4.5,
            numReviews: 10,
            shopImage: '/images/Armani.jpg',
            countInStock: 5
        },
        {
            _id: '2',
            name: 'Slim fit Soho line half-canvas suit in wool and cashmere gabardine',
            category: 'Tuxedo',
            image: '/images/d2.jpg',
            description: 'Sophisticated Soho line suit that unites tailoring tradition with precious and refined fabrics that highlight the contemporary look of the garment. The slim-fit jacket with notched lapels, a breast pocket and welt pockets. Two-button single-breasted buttoning. Length 73.5 cm - 28.9 inches The pants have a classic line, belt with loops, concealed zip and button closure. Hem width 19 cm - 7.5 inches',
            price: 2395,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 8,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '3',
            name: 'Slim-fit, half canvas wool suit from the Soho range featuring a micro-design',
            category: 'Tuxedo',
            image: '/images/d3.jpg',
            description: 'This sophisticated Soho range suit unites tailoring tradition with precious and refined fabrics that highlight the contemporary look of the garment. Slim-fit jacket with notched lapels, a breast pocket and welt pockets. Single-breasted two-button fastening. Length: 73.5 cm. The trousers have a classic line, belt with loops, concealed zip and button closure. Hem width: 19 cm.',
            price: 8995,
            brand: 'Armani',
            rating: 4.5,
            numReviews: 10,
            shopImage: '/images/Armani.jpg',
            countInStock: 6

        },
        {
            _id: '4',
            name: 'Regular-fit shirt in exclusive, finely striped fabric',
            category: 'Classic Shirts',
            image: '/images/d4.jpg',
            description: 'Regular-fit shirt made from exclusive striped fabric, with French seams, small collar with stays, back yoke and mother-of-pearl buttons.',
            price: 2395,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 8,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '5',
            name: 'Slim-fit shirt in an exclusive clean light blue jacquard',
            category: 'Classic Shirts',
            image: '/images/d5.jpg',
            description: 'Slim-fit shirt made from exclusive micro–patterned jacquard with darts at the back, collar with small points and metal stays, back yoke, mother-of-pearl buttons and French seams.',
            price: 1500,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '6',
            name: 'Nautica Classic Fit ',
            category: 'Classic Shirts',
            image: '/images/d6.jpg',
            description: 'Slim-fit shirt made from exclusive micro–patterned jacquard with darts at the back, collar with small points and metal stays, back yoke, mother-of-pearl buttons and French seams.',
            price: 1500,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '7',
            name: 'Pure silk tie with small jacquard eagles all over',
            category: 'Ties',
            image: '/images/d7.jpg',
            description: "The tie has always been a symbol of male elegance. A must-have accessory for the modern businessman and for special occasions or ceremonies. This pure silk tie stands out thanks to the jacquard weave with all-over small eagles, the symbol of the fashion house. Dimensions: 146 x 5.5 cm.",
            price: 1500,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '8',
            name: 'Pure silk tie with small jacquard eagles all over',
            category: 'Ties',
            image: '/images/d8.jpg',
            description: "The tie has always been a symbol of male elegance. A must-have accessory for the modern businessman and for special occasions or ceremonies. This pure silk tie stands out thanks to the jacquard weave with all-over small eagles, the symbol of the fashion house. Dimensions: 146 x 5.5 cm.",
            price: 1500,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '9',
            name: 'Pure silk tie with small jacquard eagles all over',
            category: 'Ties',
            image: '/images/d9.jpg',
            description: "The tie has always been a symbol of male elegance. A must-have accessory for the modern businessman and for special occasions or ceremonies. This pure silk tie stands out thanks to the jacquard weave with all-over small eagles, the symbol of the fashion house. Dimensions: 146 x 5.5 cm.",
            price: 1500,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '10',
            name: 'Fabric Three-Hand Watch',
            category: 'Accessories',
            image: '/images/d10.jpg',
            description: "The stunning chronograph dial features a stamped logo pattern and silver-tone numerals and indexes.",
            price: 1500,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '11',
            name: 'Leather Cronograph Watch',
            category: 'Accessories',
            image: '/images/d11.jpg',
            description: "Refined and elegant, the men's Esedra watch incorporates signature Emporio Armani Swiss Made lug design. A flowing facet accents the side of the polished 43mm stainless-steel case, extending down the center link of the hand-assembled three link bracelet. ",
            price: 800,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        },
        {
            _id: '12',
            name: 'Swiss Made Esedra Chronograph Watch',
            category: 'Accessories',
            image: '/images/d12.jpg',
            description: "Refined and elegant, the men's Esedra watch incorporates signature Emporio Armani Swiss Made lug design. A flowing facet accents the side of the polished 43mm stainless-steel case, extending down the center link of the hand-assembled three link bracelet. The stunning chronograph dial features a stamped logo pattern and silver-tone numerals and indexes.",
            price: 1500,
            brand: 'Armani',
            rating: 4.2,
            numReviews: 5,
            shopImage: '/images/Armani.jpg',
            countInStock: 6
        }

    ]
}